[tool.poetry]
name = "testrep"
version = "0.1.0"
description = ""
authors = ["Jan Sindlar <jan.sindlar@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
